### ISSUE TITLE
Design problems

### ISSUE THREAD

**Issue by ivan386** [ipfs-search/ipfs-search-frontend#36]
1. Preview images width bigger than container width.
2. Can't see current page
3. Can't see what last previwed link

### Need to set style rule for img: 
```css
img{
    max-width: 100%;
}
```
Before
![before](https://user-images.githubusercontent.com/717207/55669690-12bf5580-5883-11e9-9f0c-608fa7b8f63a.png)

After
![after](https://user-images.githubusercontent.com/717207/55669692-1a7efa00-5883-11e9-921e-4c7e614b0cc5.png)

### Need to show current page
```css
.page-link.current-page {
    background-color: lightgray;
}
```

Before
![pages-before](https://user-images.githubusercontent.com/717207/55669746-d9d3b080-5883-11e9-8da9-8b8223b6d062.png)

After
![pages-after](https://user-images.githubusercontent.com/717207/55669794-32a34900-5884-11e9-93d7-bd4acc538c53.png)

### Show last previwed result
```css
.selected{
    background-color: lightgray;
}
```

Before
![previwed-before](https://user-images.githubusercontent.com/717207/55669944-2d46fe00-5886-11e9-8816-3900b3103aa1.png)

After
![previwed-after](https://user-images.githubusercontent.com/717207/55669947-3768fc80-5886-11e9-8c3d-88bd8c581496.png)
